version: '0.0.1'
source: "https://github.com/tr7zw/ForgeFabricComposeTemplate/tree/1.19.2-fabriconly-mcpublish/"
replacements:
  group: "dev.tr7zw"
  name: "Exordium"
  id: "exordium"
  version: "1.0.2"
  author: "tr7zw"
  dependencies: ""
  relocationpackage: "dev.tr7zw.exordium"
  licensename: "LICENSE"
  modrinthid: "DynYZEae"
rootProject:
  template: "."
subProjects:
  FG-Fabric:
    template: "Fabric"
  FG-Forge:
    template: "Forge"